
#ifndef HEADER_COMMON
#define HEADER_COMMON

#define WINDOW_WIDTH 1280	
#define WINDOW_HEIGHT 720
#define METERS_PER_WINDOW_HEIGHT (float)32.0
#define METERS_PER_WINDOW_WIDTH (float)METERS_PER_WINDOW_HEIGHT/WINDOW_HEIGHT * WINDOW_WIDTH  //based on aspect ratio
#define PIXELS_PER_METER (float)WINDOW_HEIGHT/METERS_PER_WINDOW_HEIGHT

#define PLAYER_HEIGHT 2
#define PLAYER_WIDTH 1
#define PLATFORM_THICKNESS 2

#endif