
#define WINDOW_WIDTH 1280	
#define WINDOW_HEIGHT 720
#define METERS_PER_WINDOW_HEIGHT 50.0
#define METERS_PER_WINDOW_WIDTH METERS_PER_WINDOW_HEIGHT/WINDOW_HEIGHT * WINDOW_WIDTH  //based on aspect ratio
#define PIXELS_PER_METER WINDOW_HEIGHT/METERS_PER_WINDOW_HEIGHT